name: 'Generate client'
description: 'Greet someone and record the time'
inputs:
  language:
    required: true
    description: 'language to generate a client in. options are: csharp, go, java, php, python, ruby, shell, swift, typescript'
  openapi:
    required: true
    description: 'path to the openapi file to generate a client from'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Setup Kiota
      uses: microsoft/setup-kiota@v0.5.0
    - name: Generate client
      shell: bash
      run: kiota generate --language ${{ inputs.language }} --openapi ${{ inputs.openapi }} --output /github/workspace/generated_client
    - uses: actions/upload-artifact@v4
      with:
        path: /github/workspace/generated_client
        
