name: "Generate client"
description: "Greet someone and record the time"
inputs:
  language:
    required: true
    description: "language to generate a client in. options are: csharp, go, java, php, python, ruby, shell, swift, typescript"
  openapi:
    required: true
    description: "path to the openapi file to generate a client from"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: echo "generating client for ${{ inputs.language }} from ${{ inputs.openapi }}"
    - name: Setup Kiota
      uses: microsoft/setup-kiota@v0.5.0
      with:
        includePreRelease: true
    - name: Generate client
      shell: bash
      run: kiota generate --language ${{ inputs.language }} --openapi ${{ inputs.openapi }} --output generated_client
    - name: get artifact name
      run: file=${{ inputs.openapi }}; filename=$(basename "$file" .${file##*.}); echo client_name=${{ inputs.language }}-client-$filename >> $GITHUB_OUTPUT
      shell: bash
      id: get-artifact-name
    - uses: actions/upload-artifact@v4
      with:
        path: generated_client
        name: ${{ steps.get-artifact-name.outputs.client_name }}
