name: Generate and upload kiota client
on:
  push:
    branches:
      - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Generate artifact
          run: |
            echo "Hello, world!" > artifact.txt